from .TransportType import TransportType


# TODO: replace typed dicts with normal models

class PairingData(TypedDict, total=True):
    '''credentials to connect to the accessory'''
    Connection: TransportType
    AccessoryIP: str
    AccessoryPairingID: str # ID of the accessory provided by the accessory
    AccessoryLTPK: str # long term public key provided by the accessory
    iOSDeviceId: str # ID of the controller device (us), provided by the controller (us); uuid4 per each pairing in the current implementation, however can be the same for all pairings
    iOSDeviceLTPK: str # OUR long term PUBLIC key, generated by us for each pairing
    iOSDeviceLTSK: str # OUR long term SECRET key, generated by us for each pairing

class ControllerType(str, Enum):
    admin = auto()
    regular = auto()

class AccessoryPairings(TypedDict):
    '''all pairings of the accessory to controllers (including us)'''
    pairingId: UUID # the pairing id of the controller
    publicKey: str # the ED25519 long-term public key of the controller
    permissions: byte # bit value for the permissions
    controllerType: ControllerType # either admin or regular
