"""
Typing hints for the serialization format used by the JSON part of the HomeKit API.
"""

from __future__ import annotations
from typing import TypedDict, Union, Any
from enum import Enum, auto
from .characteristics import CharacteristicKey
from .transport_type import TransportType


Characteristic = TypedDict( # Using functional style because "valid-values" is not a valid Python identifier
    "Characteristic",
    {
        "type": str, # UUID
        "iid": int,
        "description": str,
        "value": Union[str, float, int, bool],
        "perms": list[str],
        "unit": str,
        "format": str,
        "valid-values": list[int],
        "minValue": Union[int, float],
        "maxValue": Union[int, float],
        "minStep": Union[int, float],
        "minLen": int,
    },
    total=False,
)

class Service(TypedDict, total=True):
    iid: int
    type: str # UUID
    characteristics: list[Characteristic]
    linked: list[int]

class Accessory(TypedDict, total=True):
    aid: int
    services: list[Service]

type Accessories = list[Accessory]

type HKDeviceID = str
'''HKDeviceID
”XX:XX:XX:XX:XX:XX”, where ”XX” is a hexadecimal string representing a byte, 6 bytes in total
Unique persistent MAC-like identifier for a HomeKit device (accessory).
Used in Discovery.device_id and PairingCredentials.AccessoryPairingId (the same value)
'''

class PairingCredentials(TypedDict, total=True):
    '''credentials to connect to the accessory'''
    AccessoryPairingID: HKDeviceID # ID of the accessory provided by the accessory
    AccessoryLTPK: str # long term public key provided by the accessory
    iOSDeviceId: str # ID of the controller device (us), provided by the controller (us); random uuid4 per each pairing in the current implementation, but also can be the same for all pairings. Not required to be UUID, may be 8-byte hex for real ios devices.
    iOSDeviceLTPK: str # OUR long term PUBLIC key, generated by us for each pairing
    iOSDeviceLTSK: str # OUR long term SECRET key, generated by us for each pairing

class PairingData(PairingCredentials, total=True):
    '''data in addition to credentials to connect to the accessory'''
    Connection: TransportType
    AccessoryIP: str
    # AccessoryIPs: str  # TODO: check which transports use

class AccessoryPairings(TypedDict, total=True):
    '''all pairings of the accessory to controllers (including us)'''
    pairingId: str # the pairing id of the controller (iOSDeviceId)
    publicKey: str # the ED25519 long-term public key of the controller (iOSDeviceLTPK)
    controllerType: ControllerType # either admin or regular
    permissions: bytes # bit value for the permissions

class ControllerType(str, Enum):
    admin = auto()
    regular = auto()

type Value = Any

class ResponseDict(TypedDict, total=False):
    value: Value | None
    status: int | None
    description: str | None

type Response = dict[CharacteristicKey, ResponseDict]
