"""
Typing hints for the serialization format used by the JSON part of the HomeKit API.
"""

from __future__ import annotations
from typing import TypedDict, Union, Any
from enum import Enum, auto
from uuid import UUID
from .characteristics import CharacteristicKey
from .transport_type import TransportType


Characteristic = TypedDict( # Using functional style because "valid-values" is not a valid Python identifier
    "Characteristic",
    {
        "type": str,
        "iid": int,
        "description": str,
        "value": Union[str, float, int, bool],
        "perms": list[str],
        "unit": str,
        "format": str,
        "valid-values": list[int],
        "minValue": Union[int, float],
        "maxValue": Union[int, float],
        "minStep": Union[int, float],
        "minLen": int,
    },
    total=False,
)

class Service(TypedDict, total=True):
    type: str
    iid: int
    characteristics: list[Characteristic]
    linked: list[int]

class Accessory(TypedDict, total=True):
    aid: int
    services: list[Service]

type Accessories = list[Accessory]

class PairingCredentials(TypedDict, total=True):
    '''credentials to connect to the accessory'''
    AccessoryPairingID: str # ID of the accessory provided by the accessory
    AccessoryLTPK: str # long term public key provided by the accessory
    iOSDeviceId: str # ID of the controller device (us), provided by the controller (us); uuid4 per each pairing in the current implementation, however can be the same for all pairings
    iOSDeviceLTPK: str # OUR long term PUBLIC key, generated by us for each pairing
    iOSDeviceLTSK: str # OUR long term SECRET key, generated by us for each pairing

class PairingData(PairingCredentials, total=True):
    Connection: TransportType
    AccessoryIP: str
    # AccessoryIPs: str

class ControllerType(str, Enum):
    admin = auto()
    regular = auto()

class AccessoryPairings(TypedDict, total=True):
    '''all pairings of the accessory to controllers (including us)'''
    pairingId: UUID # the pairing id of the controller
    publicKey: str # the ED25519 long-term public key of the controller
    permissions: bytes # bit value for the permissions
    controllerType: ControllerType # either admin or regular

type Value = Any

class ResponseDict(TypedDict, total=False):
    value: Value | None
    status: int | None
    description: str | None

type Response = dict[CharacteristicKey, ResponseDict]
