
class PairingDataStorageProtocol(DictStorageProtocol[UUID, PairingData]): ...

class PairingDataStorageMemory(DictStorageMemory[UUID, PairingData]): ...

class PairingDataStorageFile(DictStorageFile[UUID, PairingData]): ...
